# -*- coding: utf-8 -*-
"""Omar_232040616.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNDgjaNGIbtVi1GJ62B5W0stZyv5T7Qb
"""

pip install seaborn scikit-learn

"""#Question 1"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
iris_data = iris.data
iris_feature_names = iris.feature_names

# Convert target array to a DataFrame
iris_df = pd.DataFrame(iris_data, columns=iris_feature_names)
iris_df['target'] = iris.target

# Display basic statistics
iris_statistics = iris_df.describe()
print(iris_statistics)

# Create a pair plot
sns.set(style="ticks")
sns.pairplot(iris_df, diag_kind="kde", markers="o", hue="target", palette='viridis')
plt.show()

"""#Question 2"""

import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

# Load the Iris dataset
iris = load_iris()
X = iris.data

# Implement K-means clustering from scratch
def kmeans(X, k, max_iters=100):
    # Initialize centroids randomly
    centroids = X[np.random.choice(X.shape[0], k, replace=False)]

    for _ in range(max_iters):
        # Assign each data point to the nearest centroid
        labels = np.argmin(np.linalg.norm(X[:, np.newaxis] - centroids, axis=2), axis=1)

        # Update centroids based on the mean of data points assigned to each cluster
        new_centroids = np.array([X[labels == i].mean(axis=0) for i in range(k)])

        # Check for convergence
        if np.all(centroids == new_centroids):
            break

        centroids = new_centroids

    return labels, centroids

# Use the elbow method to determine the optimal number of clusters
def elbow_method(X, max_clusters=10):
    distortions = []

    for k in range(1, max_clusters + 1):
        labels, centroids = kmeans(X, k)
        distortion = np.sum([np.sum((X[labels == i] - centroids[i])**2) for i in range(k)])
        distortions.append(distortion)

    return distortions

# Visualize the elbow method
distortions = elbow_method(X)
plt.plot(range(1, len(distortions) + 1), distortions, marker='o')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Distortion')
plt.show()

# Based on the elbow method, let's choose an optimal K (e.g., 3 clusters)
optimal_k = 3

# Perform K-means clustering with the optimal number of clusters
labels, centroids = kmeans(X, optimal_k)

# Visualize clustered data points in a 2D scatter plot
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis', edgecolors='k')
plt.scatter(centroids[:, 0], centroids[:, 1], marker='X', s=200, c='red', label='Centroids')
plt.title('K-means Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.show()

