# -*- coding: utf-8 -*-
"""Omar_232040616.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prXwxL1GPaJ4qPCseZr0GwIqr9bBJOsU

#Question 1
"""

class Queue:
    def __init__(self):
        self.array = []

    def check_length(self):
        if len(self.array) == 0:
            print("Empty queue")
        else:
            print(f"Queue length: {len(self.array)}")

    def insert(self, num):
        self.array.append(num)
        print(f"Element {num} added to the queue")

    def remove(self):
        if len(self.array) == 0:
            print("Empty queue, cannot remove element.")
        else:
            removed_element = self.array.pop(0)
            print(f"Removed element: {removed_element}")
            self.display()

    def display(self):
        if len(self.array) == 0:
            print("Empty queue")
        else:
            print("Queue:", self.array)

q = Queue()
q.insert(10)
q.insert(15)
q.insert(5)
q.check_length()
q.remove()
q.insert(2)
q.display()
q.remove()
q.display()

"""#Questuion 2"""

import numpy as np

# Given NumPy arrays
a = np.array([4, 5, 6, 7, 8, 9])
b = np.array([10, 16, 17, 20, 18, 22])

# a) Calculate the Euclidean distance
euclidean_distance = np.linalg.norm(a - b)
print(f"a) Euclidean Distance: {euclidean_distance}")

# b) Calculate the generalised p-norm for p=3
p_norm = np.linalg.norm(a - b, ord=3)
print(f"b) Generalised p-norm (p=3): {p_norm}")

# c) Calculate the KL divergence DKL(a||b) and DKL(b||a)
kl_divergence_ab = np.sum(a * np.log(a / b))
kl_divergence_ba = np.sum(b * np.log(b / a))
# calculated directly based on the arrays a and b
print(f"c) KL Divergence DKL(a||b): {kl_divergence_ab}")
print(f"   KL Divergence DKL(b||a): {kl_divergence_ba}")

#Ensuring that arrays a and b are treated as probability distributions.
# Normalize arrays for KL divergence
a_prob = a / np.sum(a)
b_prob = b / np.sum(b)

# c) Calculate the KL divergence DKL(a||b) and DKL(b||a)
kl_divergence_ab = np.sum(a_prob * np.log(a_prob / b_prob))
kl_divergence_ba = np.sum(b_prob * np.log(b_prob / a_prob))

print(f"c) KL Divergence DKL(a||b): {kl_divergence_ab}")
print(f"   KL Divergence DKL(b||a): {kl_divergence_ba}")

"""#Question 3"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# a) Load iris data and plot class visualization
iris = sns.load_dataset('iris')

# Plot class visualization (i) "sepal_length" vs "sepal_width"
plt.figure(figsize=(10, 6))
sns.scatterplot(x='sepal_length', y='sepal_width', hue='species', data=iris)
plt.title("Class Visualization: Sepal Length vs Sepal Width")
plt.show()

# Plot class visualization (ii) "sepal_length" vs "petal_width"
plt.figure(figsize=(10, 6))
sns.scatterplot(x='sepal_length', y='petal_width', hue='species', data=iris)
plt.title("Class Visualization: Sepal Length vs Petal Width")
plt.show()

# b) Compute the centroid of data for each species
centroid_data = iris.groupby('species').mean()

# Plot centroids for each class visualization
plt.figure(figsize=(10, 6))

sns.scatterplot(x='sepal_length', y='sepal_width', hue='species', data=iris)
plt.scatter(centroid_data['sepal_length'], centroid_data['sepal_width'], marker='X', s=200, c='black', label='Centroid')
plt.title("Class Visualization with Centroids: Sepal Length vs Sepal Width")
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='sepal_length', y='petal_width', hue='species', data=iris)
plt.scatter(centroid_data['sepal_length'], centroid_data['petal_width'], marker='X', s=200, c='black', label='Centroid')
plt.title("Class Visualization with Centroids: Sepal Length vs Petal Width")
plt.legend()
plt.show()

